# Generated by Django 3.2.8 on 2021-11-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('perfil', models.CharField(max_length=255)),
                ('habilidades', models.CharField(max_length=255)),
            ],
        ),
    ]
